spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      url: ${REDIS_URL:}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}

gameio:
  security:
    refresh-cookie:
      secure: ${REFRESH_COOKIE_SECURE:true}
      same-site: ${REFRESH_COOKIE_SAME_SITE:Lax}

management:
  endpoint:
    health:
      show-details: never
